# 과제2: 커피 매장 찾기

In [1]:
# 모듈 불러오기
import pandas as pd

# 파일 불러오기
DF=pd.read_csv('hollys_branches.csv',encoding='utf-8')
DF

,매장이름,"위치(시,구)",주소,전화번호
0,종각역점,서울 종로구,서울특별시 종로구 종로 60-1 종로2가 102-3,02-736-3399
1,부산아트몰링영풍문고점,부산 사하구,"부산광역시 사하구 낙동남로 1413 (하단동, 아트몰링) 13층",051-201-0621
2,광명GIDC점,경기 광명시,"경기도 광명시 일직로 43 일직동 514 지하2층 G249, G250호",02-6914-6550
3,이천점,경기 이천시,경기도 이천시 어재연로 35 (창전동) 1~3층 할리스,031-635-6655
4,미사가로수길점,경기 하남시,"경기도 하남시 미사강변한강로 295 (망월동, 하남미사롯데캐슬헤븐시티Ⅱ) .",031-699-8674
...,...,...,...,...
524,신림점,서울 관악구,서울특별시 관악구 신림로 353-1,02-877-0019
525,태평로점,서울 중구,"서울특별시 중구 세종대로 64, 해남빌딩 1층 (태평로2가 70-5) 할리스",02-755-7795
526,이태원점,서울 용산구,서울특별시 용산구 이태원로 179,02-749-8752
527,부산서면본점,부산 부산진구,"부산광역시 부산진구 동천로 73, DS타워 1~2층 (부전동 부전동 169-1) 할리스",051-819-9117
528,신촌점,서울 서대문구,서울특별시 서대문구 연세로 34 (창천동 31-12) 할리스,02-393-2004

In [2]:
# 도시 입력받기
city=input('검색할 매장의 도시를 입력하세요:')

# 매장수 count
count=0

# 주소, 번호 저장 리스트
addr_phone=[]

# '주소' 컬럼에 입력받은 도시 있으면 리스트에 저장
for i in range(len(DF)):
    if  city.split(' ')[0] in DF['주소'][i] and city.split(' ')[1] in DF['주소'][i]:
        addr_phone.append(f"[ {count+1}]: ['{DF['주소'][i]}', {DF['전화번호'][i]}]")
        count+=1

# 결과 출력
print(f'검색된 매장 수: {count}')

for i in range(len(addr_phone)):
    print(addr_phone[i])

검색된 매장 수: 6
[ 1]: ['대구광역시 북구 동화천로 229 (연경동) 1층~2층', 053-982-6877]
[ 2]: ['대구광역시 북구 대학로 17길 3 (산격동 1393-11) 할리스 B1~3층', 053-951-9990]
[ 3]: ['대구광역시 북구 구암로 59 비전스퀘어 1,2층 .', 053-324-6122]
[ 4]: ['대구광역시 북구 침산남로 157 (침산동) .', 053-353-5544]
[ 5]: ['대구 북구 성북로 36,2층 601,602,603,604 473-3, 침산초등학교 맞은편', 053-353-5412]
[ 6]: ['대구광역시 북구 동천로 125 (동천동) .', 053-321-0099]